- type: job
  id: BlueshieldOfficer
  name: Blueshield Officer
  description: "Act as a bodyguard and advisor for Command and CentCom VIPs."
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      time: 90000 # 25 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      time: 90000 # 25 hours
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-ntr-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlue
    back: ClothingBackpackCaptain
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetBasic
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltSecurityFilled
    pocket1: UniqueBlueshieldOfficerLockerTeleporter
  storage:
    back:
    - BoxSurvival
